[build]
builder = "nixpacks"
buildCommand = "composer install && php artisan migrate:fresh --seed"

[deploy]
numReplicas = 1
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10