services:
  - type: web
    name: montana-optima
    runtime: php
    buildCommand: composer install && npm ci && npm run build && php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: MontañaOptima
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: montana-optima
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: montana_optima_db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
  
databases:
  - name: montana_optima_db
    databaseName: montana_optima
    user: montana_optima_user
    plan: free